### ISSUE TITLE
Suggestion for lazy initialization

### ISSUE THREAD

**Issue by allforabit** [andreiduca/use-async-resource#22]
For lazy initialization how about requiring that the user return a promise thunk instead of using an empty array? I.e. normal eager api:
```typescript
const fetchUser = (id: number) => Promise<User>
```
Lazy api:
```typescript
const saveUser=(user: User) => () => Promise<User>
```
This would also align it with `fp-ts` task type: https://gcanti.github.io/fp-ts/modules/Task.ts.html

**Comment by andreiduca** [comment]
I think you misread the documentation. First, `useAsyncResoource` requires the empty array for [eager initialization of API functions that don't accept arguments](https://github.com/andreiduca/use-async-resource#api-functions-that-dont-accept-parameters):

```tsx
const fetchCurrentUser = () => Promise<User>;

// in component A, eagerly initialized
const [currentUser] = useAsyncRessource(fetchCurrentUser, []);

// in component B, lazy initialized
const [lazyCurrentUser, getCurrentUser] = useAsyncRessource(fetchCurrentUser);

<button onClick={() => getCurrentUser()}>load the current user<button>
```

Second: even in your example, the `fetchUser` function is already "lazy", because the Promise it returns is never created until you actually call the function. That's exactly what this hook does for you: it calls the function, but only when you pass in whatever arguments your API function expects (in your case, the user id; or an empty array if it doesn't take any arguments):

```js
// eagerly initialized
const [user] = useAsyncRessource(fetchUser, userId); // 👈 this calls `fetchUser ` with `userId` 
```

If you don't pass any arguments, the function is lazy initialized (the `fetchUser` function is not called, so the API call is not triggered until you call the `getLazyUser` getter function):

```jsx
// lazy initialized
const [lazyUser, getLazyUser] = useAsyncRessource(fetchUser); // this doesn't call `fetchUser`

<button onClick={() => getLazyUser(userId)}>get the user<button> // 👈 only this calls `fetchUser` with `userId`
```
