### ISSUE TITLE
Error when using within a class component

### ISSUE THREAD

**Issue by mdesantis** [andreiduca/use-async-resource#28]
Hello,

maybe I just misunderstood the purpose of this library, since it has no examples related to class components; anyway, I'm trying to use it within a class component, doing something like:

```js
export default class Demo extends React.Component {
  constructor(props) {
    super(props)

    const [categoriesReader, getNewCategories] = useAsyncResource(fetchCategories, this.props.categoryId)
    this.categoriesReader = categoriesReader
    this.getNewCategories = getNewCategories
  }
}
```

But I get the following error:

```
Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
```

Is it something expected?

**Comment by andreiduca** [comment]
Hi Maurizio,

As the error suggests, you cannot use React hooks inside class components. This is by design, as hooks were introduced in React specifically to bring state management in function components.

Please check out the official docs to get a better understanding of how React hooks work: https://reactjs.org/docs/hooks-intro.html
